<template>

    <div>
        <v-chip
            v-for="(item, index) in chips" :key="'chips-' + index"
            class="ma-2"
            close
            color="primary"
            outlined
            @click:close="removeChipHandler(item)"
        >
            {{ item.name }}: {{ item.value }} 
        </v-chip>
    </div>

</template>

<script>

    import { eventHandler } from '../../local.js';

    export default {
        mixins: [],
        components: {
        },
        model: {
            event: 'change'
        },
        data() {
            return {
                chips: []
            }
        },
        created() {
            /*
                This component reacts to events generated by SearchFacetViewer.
                Listen for addChip and removeChip events.
            */
            eventHandler.listen('facet-chip-viewer.addChip', this.addChip);
            eventHandler.listen('facet-chip-viewer.removeChip', this.removeChip);
        },
        mounted() {
        },
        beforeDestroy() {
            // Stop listening for events.
            eventHandler.stopListening('facet-chip-viewer.addChip', this.addChip);
            eventHandler.stopListening('facet-chip-viewer.removeChip', this.removeChip);
        },
        methods: {
            addChip(itemToAdd) {
                // Add item to chips array; the chips array is rendered in the template, above.
                if (this.chips.findIndex(item => item.name === itemToAdd.name && item.value === itemToAdd.value) === -1) {
                    this.chips.push(itemToAdd);
                    // Emit length of chips array so that the parent view can use it to render the screen porperly
                    this.$emit('change', this.chips.length);
                }
            },
            removeChip(item) {
                // Remove item from chips array; the chips array is rendered in the template, above.
                this.chips.splice(this.chips.findIndex(chipsItem => chipsItem.name === item.name && chipsItem.value === item.value), 1);
                // Emit length of chips array so that the parent view can use it to render the screen porperly
                this.$emit('change', this.chips.length);
            },
            dispatchUnCheckItem(item) {
                /*
                    Send a message to the SearchFacetViewer component to
                    remove the appropriate facet selection.
                */
                eventHandler.dispatch(
                    'facet-viewer.' + item.name + '.removeChip',
                    item
                );
            },
            removeChipHandler(item) {
                this.dispatchUnCheckItem(item);
                this.removeChip(item);
            },
        },
        computed: {
        },
        watch: {
        }
    }

</script>

<style scoped>
</style>